on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
      - name: Publish to slack channel via bot token
        id: slack
        uses: slackapi/slack-github-action@v2-development
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C0123456789"
            text: "posting from a github action!"
