name: Local run

# Requires mocking the "public" event to begin this workflow and avoid actual runs
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  public:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v4
      - name: Build action
        run: npm install
      - name: Post a webhook message into channel
        id: webhook
        uses: ./.
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            repository: ${{ github.repository }}
            pull_request_username: ${{ github.event.pull_request.user.login }}
            pull_request_title: ${{ toJSON(github.event.pull_request.title) }}
            pull_request_url: ${{ github.event.pull_request.html_url }}
      - name: Post a token message into channel
        id: api
        uses: ./.
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Action happens at <https://github.com/${{ github.repository }}>"
      - name: Upload this workflow file
        id: file
        uses: ./.
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
            initial_comment: "This code exists here"
            file: .github/workflows/local/local.yml
            filename: action.yml
      - name: Initiate the deployment sequence
        id: slack
        uses: ./.
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Deployment started :eyes:"
            attachments:
              - color: "dbab09"
                fields:
                  - title: "Status"
                    short: true
                    value: "In Progress"
      - name: Write starting statistics
        id: stats
        uses: ./.
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ steps.slack.outputs.channel_id }}
            text: "Started at `${{ steps.slack.outputs.time }}`"
            thread_ts: ${{ steps.slack.outputs.ts }}
      - name: Countdown
        run: sleep 3
      - name: Launch time is now
        id: finished
        uses: ./.
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            ts: "${{ steps.slack.outputs.ts }}"
            text: "Deployment finished :rocket:"
            attachments:
              - color: "28a745"
                fields:
                  - title: "Status"
                    short: true
                    value: "Completed"
      - name: Celebrate wins
        uses: ./.
        with:
          method: reactions.add
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            timestamp: ${{ steps.slack.outputs.ts }}
            name: "tada"
      - name: Include ending statistics
        uses: ./.
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ steps.slack.outputs.channel_id }}
            text: "Finished at `${{ steps.finished.outputs.time }}`"
            thread_ts: ${{ steps.stats.outputs.thread_ts }}
